#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

dotnet tool run husky run --group pre-commit

## GDScript 静态检查（gdlint，只查本次暂存的 .gd）。
## 单独一个 group 是为了排在 C# 格式化之后，且不把它混进 pre-commit 组。
dotnet tool run husky run --group pre-commit-gdscript
